### ISSUE TITLE
Imaging Query Form needs better error message

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#217] opened 2016-10-31 16:37 UTC
From a bug report filed by a SciServer user:

--------------------------------------------------------------
Issue title: Imaging Query Form Error

From: Amanda Newmark

Category: Error message needed

Severity: Mild

Description:
I get the following error:

Exception of type 'System.Web.HttpUnhandledException' was thrown.: Input string was not in a correct format.

Steps to reproduce:
1. no limit
2. imaging parameters set to radec
3. Rectangle parameters:
RA 212.7 223.4
DEC -2.5 2.26

**Comment by raddick** [comment] 2016-10-31 16:40
Bug report filed by:

Amanda Newmark
Princeton University
anewmark@princeton.edu
October 15, 2016 at 1:19 PM

**Comment by mtaghiza** [comment] 2016-10-31 17:16
Cannot reproduce the error from the user, but at least this unleashed my finding a bug in the error message shown to the user when the DEC values are off limits.

When try to reproduce the user's procedure, I actually get a valid error message: 
An error occured
Invalid numerical value for maximum number of rows in LIMIT=

If I include a valid value for the limit, then I get an error message which is a little wrong:

Incorrect syntax near 'Illegal'. Incorrect syntax near 'pERROR:'.

Your SQL command was: 
ERROR: Illegal rectangular search values: 212.7,223.4,-2.5,2.26.
SELECT TOP 10 
cast(str(p.ra,13,8) as float) as ra,cast(str(p.[dec],13,8) as float) as dec 
FROM ..PhotoObj AS pERROR: Illegal rectangular search values: 212.7,223.4,-2.5,2.26. 
WHERE  ( p.type = 3 OR p.type = 6)

**Comment by mtaghiza** [comment] 2017-02-13 20:59
Fixed in 1.9.1

**Closed as completed by mtaghiza** 2017-02-13 20:59 UTC
Labels: errorhandling, sciserver_v1_8_2
