### ISSUE TITLE
Entering row limit > 1000  (but < 500,000) in IQS and SQS returns error

### ISSUE THREAD

**Issue by thakar** [sciserver/SkyServer#176] opened 2015-12-10 20:28 UTC
If I change the value for the row limit at the top of the Imaging or Spectro Query form (also the IR Spec query form) to any value > 1000 (but within the 500k max value), I get the following error message:

Your SQL command was: 
SELECT TOP 1001 
s.plate,s.mjd,s.fiberid 
FROM ..SpecObj as s 
JOIN dbo.fGetNearbySpecObjEq(10,0.2,5.0) AS b ON  b.SpecobjID = S.SpecobjID 
WHERE  s.zWarning = 0 

Error: Maximum number of rows is 500,000. Try using 'TOP 500000' in the SQL command.

**Comment by mtaghiza** [comment] 2015-12-10 21:12
It is basically taking the default value from spExecuteSQL, since it was not given one in the code. I had already fixed this after the release, so it will be not showing this anymore (max will always be 500,000).
Please confirm for next release.

**Comment by mtaghiza** [comment] 2016-08-05 21:35
Confirmed that is fixed, as of production version sciserver-v1.8.1. Closing...

**Closed by mtaghiza** 2016-08-05 21:35 UTC
Labels: needstest, sciserver_v1_6_1
