### ISSUE TITLE
History: cannot filter for Explore results only (but Finding Chart and SQL Search work fine)

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#181] opened 2016-05-02 13:34 UTC
On the SkyServer History page, filtering the history results for Finding Chart or SQL Search works fine, but filtering for Explore results shows all results instead. Screenshot:

![explore_filtering_bug](https://cloud.githubusercontent.com/assets/1709156/14956924/692f9cd2-1050-11e6-9777-79dc1a5584f6.png)

This is browser-independent.

**Comment by mikear69** [comment] 2016-05-02 14:24
This looks like the incorrect screenshot.

**Comment by raddick** [comment] 2016-05-02 14:27
Indeed that was the wrong screenshot. Replaced with the correct one. Thanks.

**Comment by mikear69** [comment] 2016-05-02 15:35
I did some more testing because I had this issue.  I think it fails to filter by whatever is the first listed query type in the list.  Try running a query with a name that is alphabetically lower than "Explore" and then try and filter by Explore and it will probably work.

**Comment by thakar** [comment] 2016-05-02 17:51
Also, if you type in "explore" in the keyword input field, it does filter
by "Explore Tool".

    Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Love all, trust a few, do wrong to none. [Shakespeare]

**Comment by mtaghiza** [comment] 2016-05-05 00:06
Fixed. Just committed the code to github. I left to you guys pushing to test/production, etc

**Comment by mtaghiza** [comment] 2016-08-05 21:44
Confirmed the fix in production skyserver version sciserver-v1.8.1. Closing...

**Closed by mtaghiza** 2016-08-05 21:44 UTC
Labels: bug, needstest
